change log file handling

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -362,13 +362,13 @@ jobs:
         if: always() && inputs.check_postgres_logs
         uses: jwalton/gh-docker-logs@v2
         with:
-          dest: '${{ runner.workspace }}/logs-docker'
+          dest: '${RUNNER_TEMP}/logs-docker'
 
       - name: 🐞 Check docker logs for PostgreSQL ERRORs
         if: always() && inputs.check_postgres_logs
         run: |
           ## --------------------------------------------------------------------
-          log=$(find ${{ runner.workspace }}/logs-docker/ -name '*postgres*.log')
+          log=$(find ${RUNNER_TEMP}/logs-docker/ -name '*postgres*.log')
 
           errors=$(awk '/(ERROR:|STATEMENT:)/{flag=1}/LOG:|^[A-Z]/{flag=0}flag {print $0}' $log)
 
@@ -558,15 +558,22 @@ jobs:
         if: always()
         uses: jwalton/gh-docker-logs@v2
         with:
-          dest: '${{ runner.workspace }}/logs-docker'
+          dest: '${RUNNER_TEMP}/logs-docker'
 
       - name: 🐞 Check docker logs for SQL Server ERRORs
         if: always()
         run: |
-          ## --------------------------------------------------------------------
-          log=$(find ${{ runner.workspace }}/logs-docker/ -name 'sql.log')
+          log=$(find ${RUNNER_TEMP}/logs-docker/ -name 'sql.log')
 
           cat "$log"
+
+          # Check for errors in the log
+          errors=$(grep -iE "Error:|Severity: (1[6-9]|2[0-5])|Msg [0-9]+, Level (1[6-9]|2[0-5])" "$log" || true)
+          if [[ -n "$errors" ]]; then
+            echo "Found errors in SQL Server logs:"
+            echo "$errors"
+            exit 1
+          fi
 
 
   code-coverage-oracle:
@@ -779,16 +786,15 @@ jobs:
           fi
         shell: bash
 
-      - name: 🐞 Collect podman logs
+      - name: 🐞 Collect docker logs
         if: always()
         run: |
-          podman logs oracledb > ${{ runner.workspace }}/oracle.log
+          podman logs oracledb > ${RUNNER_TEMP}/oracle.log
 
-      - name: 🐞 Check podman logs for Oracle ERRORs
+      - name: 🐞 Check docker logs for Oracle ERRORs
         if: always()
         run: |
-          ## --------------------------------------------------------------------
-          log="${{ runner.workspace }}/oracle.log"
+          log=$(find ${RUNNER_TEMP}/logs-docker/ -name 'sql.log')
 
           cat "$log"
 
