fix: Shorten grep expressions - Director's Cut

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -85,15 +85,8 @@ jobs:
           cat $TESTTHAT_OUT
 
           # Throw errors on failures or warnings
-          if [ $(grep -c "FAIL 0" $TESTTHAT_OUT) -eq 0 ]; then
-            echo "Test failures found"
-            exit 1
-          fi
-
-          if [ $(grep -c "WARN 0" $TESTTHAT_OUT) -eq 0 ]; then
-            echo "Test warnings found"
-            exit 1
-          fi
+          grep -q "FAIL 0" $TESTTHAT_OUT || { echo "Test failures found"; exit 1; }
+          grep -q "WARN 0" $TESTTHAT_OUT || { echo "Test warnings found"; exit 1; }
         shell: bash
 
       - name: Upload test results
@@ -171,15 +164,9 @@ jobs:
           cat $TESTTHAT_OUT
 
           # Throw errors on failures or warnings
-          if [ $(grep -c "FAIL 0" $TESTTHAT_OUT) -eq 0 ]; then
-            echo "Test failures found"
-            exit 1
-          fi
+          grep -q "FAIL 0" $TESTTHAT_OUT || { echo "Test failures found"; exit 1; }
+          grep -q "WARN 0" $TESTTHAT_OUT || { echo "Test warnings found"; exit 1; }
 
-          if [ $(grep -c "WARN 0" $TESTTHAT_OUT) -eq 0 ]; then
-            echo "Test warnings found"
-            exit 1
-          fi
         shell: bash
 
       - name: Upload test results
@@ -262,15 +249,8 @@ jobs:
           cat $TESTTHAT_OUT
 
           # Throw errors on failures or warnings
-          if [ $(grep -c "FAIL 0" $TESTTHAT_OUT) -eq 0 ]; then
-            echo "Test failures found"
-            exit 1
-          fi
-
-          if [ $(grep -c "WARN 0" $TESTTHAT_OUT) -eq 0 ]; then
-            echo "Test warnings found"
-            exit 1
-          fi
+          grep -q "FAIL 0" $TESTTHAT_OUT || { echo "Test failures found"; exit 1; }
+          grep -q "WARN 0" $TESTTHAT_OUT || { echo "Test warnings found"; exit 1; }
         shell: bash
 
       - name: Upload test results
