fix(code-coverage): Exit with success if no ERROR: (Postgres)

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -190,10 +190,15 @@ jobs:
           ## --------------------------------------------------------------------
           log=$(find ${{ runner.workspace }}/logs-docker/ -name '*postgres*.log')
 
-          awk '/(ERROR:|STATEMENT:)/{flag=1}/LOG:|^[A-Z]/{flag=0}flag {print $0}' $log
+          errors=$(awk '/(ERROR:|STATEMENT:)/{flag=1}/LOG:|^[A-Z]/{flag=0}flag {print $0}' $log)
+
+          echo "$output"
 
           # Throw error if ERRORs are found
-          grep -q "ERROR:" $log && { echo "PostgreSQL ERRORs found"; exit 1; }
+          if [[ -n "$errors" ]]; then
+            echo "$errors"
+            exit 1
+          fi
 
   code-coverage-mssql:
     name: 🧪 Tests (SQL Server 2019)
