fix(code-coverage): disable sqlite wf temporarily

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -10,43 +10,44 @@ on:
 
 
 jobs:
-  code-coverage-sqlite:
-    name: 🧪 Running tests
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
+  # code-coverage-sqlite:
+  #   name: 🧪 Running tests
+  #   runs-on: ubuntu-latest
+  #   if: false()
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          use-public-rspm: true
+  #     - uses: r-lib/actions/setup-r@v2
+  #       with:
+  #         use-public-rspm: true
 
-      - uses: r-lib/actions/setup-r-dependencies@v2
-        with:
-          extra-packages: any::covr
-          needs: coverage
+  #     - uses: r-lib/actions/setup-r-dependencies@v2
+  #       with:
+  #         extra-packages: any::covr
+  #         needs: coverage
 
-      - name: Test coverage
-        run: |
-          covr::codecov(
-            quiet = FALSE,
-            clean = FALSE,
-            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
-          )
-        shell: Rscript {0}
+  #     - name: Test coverage
+  #       run: |
+  #         covr::codecov(
+  #           quiet = FALSE,
+  #           clean = FALSE,
+  #           install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+  #         )
+  #       shell: Rscript {0}
 
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+  #     - name: Show testthat output
+  #       if: always()
+  #       run: |
+  #         ## --------------------------------------------------------------------
+  #         find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+  #       shell: bash
 
-      - name: Upload test results
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: coverage-test-failures
-          path: ${{ runner.temp }}/package
+  #     - name: Upload test results
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: coverage-test-failures
+  #         path: ${{ runner.temp }}/package
 
 
   code-coverage-postgres:
