Revert "feat(code-coverage): shorten grep expressions"
This reverts commit 1b0eb2fadc79801b9d391c4e076f13e71332684e.

diff --git a/.github/workflows/code-coverage.yaml b/.github/workflows/code-coverage.yaml
--- a/.github/workflows/code-coverage.yaml
+++ b/.github/workflows/code-coverage.yaml
@@ -85,8 +85,15 @@ jobs:
           cat $TESTTHAT_OUT
 
           # Throw errors on failures or warnings
-          [[ $(grep -q "FAIL 0" $TESTTHAT_OUT) ]] || { echo "Test failures found"; exit 1; }
-          [[ $(grep -q "WARN 0" $TESTTHAT_OUT) ]] || { echo "Test warnings found"; exit 1; }
+          if [ $(grep -c "FAIL 0" $TESTTHAT_OUT) -eq 0 ]; then
+            echo "Test failures found"
+            exit 1
+          fi
+
+          if [ $(grep -c "WARN 0" $TESTTHAT_OUT) -eq 0 ]; then
+            echo "Test warnings found"
+            exit 1
+          fi
         shell: bash
 
       - name: Upload test results
@@ -164,8 +171,15 @@ jobs:
           cat $TESTTHAT_OUT
 
           # Throw errors on failures or warnings
-          [[ $(grep -q "FAIL 0" $TESTTHAT_OUT) ]] || { echo "Test failures found"; exit 1; }
-          [[ $(grep -q "WARN 0" $TESTTHAT_OUT) ]] || { echo "Test warnings found"; exit 1; }
+          if [ $(grep -c "FAIL 0" $TESTTHAT_OUT) -eq 0 ]; then
+            echo "Test failures found"
+            exit 1
+          fi
+
+          if [ $(grep -c "WARN 0" $TESTTHAT_OUT) -eq 0 ]; then
+            echo "Test warnings found"
+            exit 1
+          fi
         shell: bash
 
       - name: Upload test results
@@ -248,8 +262,15 @@ jobs:
           cat $TESTTHAT_OUT
 
           # Throw errors on failures or warnings
-          [[ $(grep "FAIL 0" $TESTTHAT_OUT) ]] || { echo "Test failures found"; exit 1; }
-          [[ $(grep "WARN 0" $TESTTHAT_OUT) ]] || { echo "Test warnings found"; exit 1; }
+          if [ $(grep -c "FAIL 0" $TESTTHAT_OUT) -eq 0 ]; then
+            echo "Test failures found"
+            exit 1
+          fi
+
+          if [ $(grep -c "WARN 0" $TESTTHAT_OUT) -eq 0 ]; then
+            echo "Test warnings found"
+            exit 1
+          fi
         shell: bash
 
       - name: Upload test results
